export const FintechPrimitiveUrl = process.env.NEXT_PUBLIC_FINTECH_PRIMITIVE_URL!;
export const FintechPrimitiveUrlV2= process.env.NEXT_PUBLIC_FINTECH_PRIMITIVE_V2_TEST_URL!;
export const ClientId = process.env.NEXT_PUBLIC_FINTECH_PRIMITIVE_CLIENT_ID!;
export const ClientSecret = process.env.NEXT_PUBLIC_FINTECH_PRIMITIVE_CLIENT_SECRET!;
export const GrantType = process.env.NEXT_PUBLIC_FINTECH_PRIMITIVE_GRANT_TYPE!;
export const AccessTokenKey = "access_token";
export const TenantKey = "tenant";
export const KycIdKey = "kyc_id";
export const CurrentStepId = "current_step_id";